### ISSUE TITLE
Afterburner profiles

### ISSUE THREAD

**Issue by Dobsgw** [CaldurG/MinerLauncher#1]
Hey this tool is awesome for part time mining!

The only issue I have:
Afterburner profiles aren't changing. Always stuck on the mining settings.

Any suggestions? I just setup the scheduled task for login and everything starts correctly.

BTW Windows defender does sometimes detect this as a virus so it needs to be excluded after being scheduled

**Comment by CaldurG** [comment]
Hi, thx for trying out the tool :) Are you running the task with highest privileges? I added "Task" folder with MinerLauncher.xml that can be imported into task scheduler and some screenshots with stuff what is important to set during task creation. And are your gaming and mining profile on position 1 and 2 in Afterburner? If not you have to change it in configuration file.

**Comment by Dobsgw** [comment]
Haha yeah you predicted everyone's profiles. 1 for games 2 for mining. Priorities I guess :P

Your task setup instructions work perfectly. Now the tool is working as expected, AB profiles are changing and task starts correctly.

It seems to be important to paste the tool into program files. 

The .xml task import works but all the user info comes from your PC and profile so I ended up making the task manually. 

Let's close this issue :)
